using SmartIndexManager.Core.Ddl;
using SmartIndexManager.Core.Provider;
using SmartIndexManager.Core.Sql;

namespace SmartIndexManager.Providers.SqlServer;

public sealed partial class SqlServerIndexProvider
{
    public Task DropIndexAsync(IndexRef index, TimeSpan timeout, CancellationToken cancellationToken = default)
    {
        if (!Permissions.CanAlter)
            throw new InvalidOperationException("DROP INDEX requires ALTER permission, which the current login lacks.");

        return ExclusiveAsync(async ct =>
        {
            await UseDatabaseAsync(index.Database, ct).ConfigureAwait(false);

            // Defence in depth: refuse anything that is not a plain nonclustered rowstore non-unique DROP
            // INDEX target, even though the caller (Core DeletionSafetyEvaluator) should already have gated it.
            var check = SqlScriptLoader.Load(_scriptRoot, "index-droppable-check");
            var droppable = await _executor.ScalarAsync<bool?>(check,
                new Dictionary<string, object?>
                {
                    ["@SchemaName"] = index.Schema, ["@TableName"] = index.Table, ["@IndexName"] = index.Index
                },
                ct).ConfigureAwait(false);
            if (droppable != true)
                throw new InvalidOperationException(
                    $"Index {index.Schema}.{index.Table}.{index.Index} is not a droppable nonclustered rowstore non-unique index; refusing DROP.");

            // Identifiers cannot be parameterized; the statement is generated by the shared DDL
            // generator (bracket-quoted, ]] escaped). The caller has already gated eligibility.
            var sql = SqlServerDdlGenerator.GenerateDropStatement(index.Schema, index.Table, index.Index);
            await _executor.ExecuteAsync(sql, null, timeout, ct).ConfigureAwait(false);
        }, cancellationToken);
    }

    public Task EnableQueryStoreAsync(
        string database, QueryStoreSettings settings, CancellationToken cancellationToken = default)
    {
        if (!Capabilities.SupportsQueryStore)
            throw new InvalidOperationException("Query Store is not supported on this server.");
        if (!Permissions.CanAlter)
            throw new InvalidOperationException("Enabling Query Store requires ALTER permission, which the current login lacks.");

        return ExclusiveAsync(async ct =>
        {
            await UseDatabaseAsync(database, ct).ConfigureAwait(false);

            var script = SqlScriptLoader.Load(_scriptRoot, "querystore-enable");
            var parameters = new Dictionary<string, object?>
            {
                ["@DatabaseName"] = database,
                ["@MaxStorageSizeMb"] = settings.MaxStorageSizeMb,
                ["@StaleQueryThresholdDays"] = settings.StaleQueryThresholdDays
            };
            await _executor.ScalarAsync<bool?>(script, parameters, ct).ConfigureAwait(false);
        }, cancellationToken);
    }

    public Task ExecuteDdlAsync(string database, string sql, CancellationToken cancellationToken = default)
        => ExclusiveAsync(async ct =>
        {
            if (!await DatabaseExistsAsync(database, ct).ConfigureAwait(false))
                throw new InvalidOperationException($"unknown database: {database}");

            await UseDatabaseAsync(database, ct).ConfigureAwait(false);
            await _executor.ExecuteAsync(sql, null, timeout: null, ct).ConfigureAwait(false);
        }, cancellationToken);

    public Task<bool> IndexExistsAsync(
        string database, string schema, string table, string index,
        CancellationToken cancellationToken = default)
        => ExclusiveAsync(async ct =>
        {
            if (!await DatabaseExistsAsync(database, ct).ConfigureAwait(false)) return false;

            await UseDatabaseAsync(database, ct).ConfigureAwait(false);
            var indexScript = SqlScriptLoader.Load(_scriptRoot, "index-exists");
            return await _executor.ScalarAsync<bool>(indexScript, new Dictionary<string, object?>
            {
                ["@SchemaName"] = schema,
                ["@TableName"] = table,
                ["@IndexName"] = index
            }, ct).ConfigureAwait(false);
        }, cancellationToken);

    public Task<bool> TableExistsAsync(
        string database, string schema, string table,
        CancellationToken cancellationToken = default)
        => ExclusiveAsync(async ct =>
        {
            if (!await DatabaseExistsAsync(database, ct).ConfigureAwait(false)) return false;

            await UseDatabaseAsync(database, ct).ConfigureAwait(false);
            var tableScript = SqlScriptLoader.Load(_scriptRoot, "table-exists");
            return await _executor.ScalarAsync<bool>(tableScript, new Dictionary<string, object?>
            {
                ["@SchemaName"] = schema,
                ["@TableName"] = table
            }, ct).ConfigureAwait(false);
        }, cancellationToken);

    // Runs the server-side existence check for a database. Assumes the caller already holds
    // the connection gate; it does not switch database (DB_ID works from any context).
    private async Task<bool> DatabaseExistsAsync(string database, CancellationToken ct)
    {
        var script = SqlScriptLoader.Load(_scriptRoot, "database-exists");
        return await _executor.ScalarAsync<bool>(
            script, new Dictionary<string, object?> { ["@DatabaseName"] = database }, ct).ConfigureAwait(false);
    }
}
