//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartIndexManager.App.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SmartIndexManager.App.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        internal static string Action_Connect {
            get {
                return ResourceManager.GetString("Action_Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Action_Cancel {
            get {
                return ResourceManager.GetString("Action_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string Action_Refresh {
            get {
                return ResourceManager.GetString("Action_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database.
        /// </summary>
        internal static string Grid_Column_Database {
            get {
                return ResourceManager.GetString("Grid_Column_Database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schema.
        /// </summary>
        internal static string Grid_Column_Schema {
            get {
                return ResourceManager.GetString("Grid_Column_Schema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table.
        /// </summary>
        internal static string Grid_Column_Table {
            get {
                return ResourceManager.GetString("Grid_Column_Table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index.
        /// </summary>
        internal static string Grid_Column_Index {
            get {
                return ResourceManager.GetString("Grid_Column_Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string Grid_Column_Type {
            get {
                return ResourceManager.GetString("Grid_Column_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score.
        /// </summary>
        internal static string Grid_Column_Score {
            get {
                return ResourceManager.GetString("Grid_Column_Score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not deletable.
        /// </summary>
        internal static string Badge_NotDeletable {
            get {
                return ResourceManager.GetString("Badge_NotDeletable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FK.
        /// </summary>
        internal static string Badge_ForeignKey {
            get {
                return ResourceManager.GetString("Badge_ForeignKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hint.
        /// </summary>
        internal static string Badge_Hint {
            get {
                return ResourceManager.GetString("Badge_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redundant.
        /// </summary>
        internal static string Badge_Redundant {
            get {
                return ResourceManager.GetString("Badge_Redundant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage statistics unavailable (missing VIEW SERVER STATE / VIEW DATABASE STATE).
        /// </summary>
        internal static string Permission_UsageUnavailable {
            get {
                return ResourceManager.GetString("Permission_UsageUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read-only: ALTER permission missing.
        /// </summary>
        internal static string Permission_ReadOnly {
            get {
                return ResourceManager.GetString("Permission_ReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observed since {0}.
        /// </summary>
        internal static string Detail_OldestSnapshot {
            get {
                return ResourceManager.GetString("Detail_OldestSnapshot", resourceCulture);
            }
        }
    }
}
