//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartIndexManager.App.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SmartIndexManager.App.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        public static string Action_Connect {
            get {
                return ResourceManager.GetString("Action_Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Action_Cancel {
            get {
                return ResourceManager.GetString("Action_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string Action_Refresh {
            get {
                return ResourceManager.GetString("Action_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SmartIndexManager.
        /// </summary>
        public static string App_Title {
            get {
                return ResourceManager.GetString("App_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string Grid_Filter {
            get {
                return ResourceManager.GetString("Grid_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Databases (comma separated).
        /// </summary>
        public static string Connection_DatabasesWatermark {
            get {
                return ResourceManager.GetString("Connection_DatabasesWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DDL.
        /// </summary>
        public static string Detail_Ddl {
            get {
                return ResourceManager.GetString("Detail_Ddl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queries.
        /// </summary>
        public static string Detail_Queries {
            get {
                return ResourceManager.GetString("Detail_Queries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hints.
        /// </summary>
        public static string Detail_Hints {
            get {
                return ResourceManager.GetString("Detail_Hints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score factors.
        /// </summary>
        public static string Detail_ScoreFactors {
            get {
                return ResourceManager.GetString("Detail_ScoreFactors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database.
        /// </summary>
        public static string Grid_Column_Database {
            get {
                return ResourceManager.GetString("Grid_Column_Database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schema.
        /// </summary>
        public static string Grid_Column_Schema {
            get {
                return ResourceManager.GetString("Grid_Column_Schema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table.
        /// </summary>
        public static string Grid_Column_Table {
            get {
                return ResourceManager.GetString("Grid_Column_Table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index.
        /// </summary>
        public static string Grid_Column_Index {
            get {
                return ResourceManager.GetString("Grid_Column_Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Grid_Column_Type {
            get {
                return ResourceManager.GetString("Grid_Column_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unique.
        /// </summary>
        public static string Grid_Column_Unique {
            get {
                return ResourceManager.GetString("Grid_Column_Unique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score.
        /// </summary>
        public static string Grid_Column_Score {
            get {
                return ResourceManager.GetString("Grid_Column_Score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key.
        /// </summary>
        public static string Grid_Column_Key {
            get {
                return ResourceManager.GetString("Grid_Column_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Includes.
        /// </summary>
        public static string Grid_Column_Includes {
            get {
                return ResourceManager.GetString("Grid_Column_Includes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string Grid_Column_Filter {
            get {
                return ResourceManager.GetString("Grid_Column_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last read.
        /// </summary>
        public static string Grid_Column_LastRead {
            get {
                return ResourceManager.GetString("Grid_Column_LastRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size (MB).
        /// </summary>
        public static string Grid_Column_SizeMb {
            get {
                return ResourceManager.GetString("Grid_Column_SizeMb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seeks.
        /// </summary>
        public static string Grid_Column_Seeks {
            get {
                return ResourceManager.GetString("Grid_Column_Seeks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scans.
        /// </summary>
        public static string Grid_Column_Scans {
            get {
                return ResourceManager.GetString("Grid_Column_Scans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updates.
        /// </summary>
        public static string Grid_Column_Updates {
            get {
                return ResourceManager.GetString("Grid_Column_Updates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not deletable.
        /// </summary>
        public static string Badge_NotDeletable {
            get {
                return ResourceManager.GetString("Badge_NotDeletable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FK.
        /// </summary>
        public static string Badge_ForeignKey {
            get {
                return ResourceManager.GetString("Badge_ForeignKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hint.
        /// </summary>
        public static string Badge_Hint {
            get {
                return ResourceManager.GetString("Badge_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redundant.
        /// </summary>
        public static string Badge_Redundant {
            get {
                return ResourceManager.GetString("Badge_Redundant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage statistics unavailable (missing VIEW SERVER STATE / VIEW DATABASE STATE).
        /// </summary>
        public static string Permission_UsageUnavailable {
            get {
                return ResourceManager.GetString("Permission_UsageUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read-only: ALTER permission missing.
        /// </summary>
        public static string Permission_ReadOnly {
            get {
                return ResourceManager.GetString("Permission_ReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observed since {0}.
        /// </summary>
        public static string Detail_OldestSnapshot {
            get {
                return ResourceManager.GetString("Detail_OldestSnapshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection failed.
        /// </summary>
        public static string Connection_Error {
            get {
                return ResourceManager.GetString("Connection_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load detail.
        /// </summary>
        public static string Detail_Error {
            get {
                return ResourceManager.GetString("Detail_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Integrated authentication needs Windows or a Kerberos-configured host. Use SQL or Entra ID instead..
        /// </summary>
        public static string Auth_WindowsIntegratedUnavailable {
            get {
                return ResourceManager.GetString("Auth_WindowsIntegratedUnavailable", resourceCulture);
            }
        }

        public static string Action_ToggleTheme {
            get {
                return ResourceManager.GetString("Action_ToggleTheme", resourceCulture);
            }
        }

        public static string Connection_Title {
            get {
                return ResourceManager.GetString("Connection_Title", resourceCulture);
            }
        }

        public static string Connection_Add {
            get {
                return ResourceManager.GetString("Connection_Add", resourceCulture);
            }
        }

        public static string Connection_Save {
            get {
                return ResourceManager.GetString("Connection_Save", resourceCulture);
            }
        }

        public static string Connection_Delete {
            get {
                return ResourceManager.GetString("Connection_Delete", resourceCulture);
            }
        }

        public static string Connection_Name {
            get {
                return ResourceManager.GetString("Connection_Name", resourceCulture);
            }
        }

        public static string Connection_Server {
            get {
                return ResourceManager.GetString("Connection_Server", resourceCulture);
            }
        }

        public static string Connection_Port {
            get {
                return ResourceManager.GetString("Connection_Port", resourceCulture);
            }
        }

        public static string Connection_Auth {
            get {
                return ResourceManager.GetString("Connection_Auth", resourceCulture);
            }
        }

        public static string Connection_Login {
            get {
                return ResourceManager.GetString("Connection_Login", resourceCulture);
            }
        }

        public static string Connection_Encrypt {
            get {
                return ResourceManager.GetString("Connection_Encrypt", resourceCulture);
            }
        }

        public static string Connection_TrustServerCertificate {
            get {
                return ResourceManager.GetString("Connection_TrustServerCertificate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Audit.
        /// </summary>
        public static string Nav_Audit {
            get {
                return ResourceManager.GetString("Nav_Audit", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Deletion basket.
        /// </summary>
        public static string Nav_Basket {
            get {
                return ResourceManager.GetString("Nav_Basket", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string Nav_Browse {
            get {
                return ResourceManager.GetString("Nav_Browse", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Restore.
        /// </summary>
        public static string Nav_Restore {
            get {
                return ResourceManager.GetString("Nav_Restore", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Nav_Settings {
            get {
                return ResourceManager.GetString("Nav_Settings", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Planned for a future version..
        /// </summary>
        public static string Placeholder_Message {
            get {
                return ResourceManager.GetString("Placeholder_Message", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Disconnect.
        /// </summary>
        public static string Connection_Disconnect {
            get {
                return ResourceManager.GetString("Connection_Disconnect", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Manage….
        /// </summary>
        public static string Connection_Manage {
            get {
                return ResourceManager.GetString("Connection_Manage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Connect to a server to browse indexes..
        /// </summary>
        public static string Connection_Prompt {
            get {
                return ResourceManager.GetString("Connection_Prompt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} of {1} indexes.
        /// </summary>
        public static string Grid_MatchCount {
            get {
                return ResourceManager.GetString("Grid_MatchCount", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No indexes.
        /// </summary>
        public static string Grid_EmptyTitle {
            get {
                return ResourceManager.GetString("Grid_EmptyTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Connect to a server to browse indexes..
        /// </summary>
        public static string Grid_EmptyMessage {
            get {
                return ResourceManager.GetString("Grid_EmptyMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No matches.
        /// </summary>
        public static string Grid_NoMatchesTitle {
            get {
                return ResourceManager.GetString("Grid_NoMatchesTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No index matches the current filter..
        /// </summary>
        public static string Grid_NoMatchesMessage {
            get {
                return ResourceManager.GetString("Grid_NoMatchesMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Clear filter.
        /// </summary>
        public static string Grid_ClearFilter {
            get {
                return ResourceManager.GetString("Grid_ClearFilter", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Select an index to see its details..
        /// </summary>
        public static string Detail_Empty {
            get {
                return ResourceManager.GetString("Detail_Empty", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string Detail_Copy {
            get {
                return ResourceManager.GetString("Detail_Copy", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Structure.
        /// </summary>
        public static string Detail_Section_Structure {
            get {
                return ResourceManager.GetString("Detail_Section_Structure", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Usage.
        /// </summary>
        public static string Detail_Section_Usage {
            get {
                return ResourceManager.GetString("Detail_Section_Usage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Provider properties.
        /// </summary>
        public static string Detail_Section_ProviderProps {
            get {
                return ResourceManager.GetString("Detail_Section_ProviderProps", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Deleting indexes....
        /// </summary>
        public static string Action_Delete {
            get {
                return ResourceManager.GetString("Action_Delete", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Reliability: {0}.
        /// </summary>
        public static string DryRun_Reliability {
            get {
                return ResourceManager.GetString("DryRun_Reliability", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} indexes, {1:0.0} MB freed.
        /// </summary>
        public static string DryRun_Summary {
            get {
                return ResourceManager.GetString("DryRun_Summary", resourceCulture);
            }
        }
    }
}
